project:
  type: website

website:
  title: "Our website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

      - href: data_documentation.qmd
        text: Data documentation

      - href: analysis_report.qmd
        text: Analysis report


format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true



